#------------------------------------------------------------------------------------
# \u7F13\u5B58\u952E\u524D\u7F00\u914D\u7F6E\u3002
#------------------------------------------------------------------------------------
# \u5BA1\u8BA1\u7C7B\u522B\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.audit.cache.prefix.entity.audit_category=com.dwarfeng.audit.entity.audit_category.
# \u5BA1\u8BA1\u5C5E\u6027\u6307\u793A\u5668\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.audit.cache.prefix.entity.audit_property_indicator=com.dwarfeng.audit.entity.audit_property_indicator.
# \u5BA1\u8BA1\u6761\u76EE\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.audit.cache.prefix.entity.audit_entry=com.dwarfeng.audit.entity.audit_entry.
# \u5BA1\u8BA1\u6761\u76EE\u5C5E\u6027\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.audit.cache.prefix.entity.audit_entry_property=com.dwarfeng.audit.entity.audit_entry_property.
