com.dwarfeng.audit.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.audit.jdbc.url=jdbc:mysql://your-host-here:3306/audit?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.audit.jdbc.username=root
com.dwarfeng.audit.jdbc.password=your-password-here
com.dwarfeng.audit.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
